GET http://localhost:5000/transaction

###
GET http://localhost:5000/transaction/1

###
POST http://localhost:5000/transaction
Content-Type: application/json

{
    "label" : "Berhasil",
    "idtrans" : "IDTrans04_23102022",
    "paymenttype" : "Transfer",
    "price" : 235000,
    "date" : "2022-10-23",
    "member" : "Member"

}

###
PATCH http://localhost:5000/transaction/1
Content-Type: application/json

{
    "label" : "Berhasil",
    "idtrans" : "IDTrans01_23102022",
    "paymenttype" : "Cash",
    "price" : 100.000,
    "date" : "2022-10-23",
    "member" : "Non-Member"

}

###
DELETE http://localhost:5000/transaction/2

###
GET http://localhost:5000/transaction/total